### ISSUE TITLE
The only way to select a boot device is rebooting throughout the script 

### ISSUE THREAD

**Issue by k2arim99** [MrChromebox/scripts#173]
Title, my device is a 2013 pixel link, is this intended behavior?, Had no issues with the installation

**Comment by MrChromebox** [comment]
I have no idea what you are trying to say

**Comment by k2arim99** [comment]
When I reboot and control L to legacy mode I get directly to "booting from the hard drive", when I reboot from the firmware-util.sh script I get to choose the boot drive correctly

**Comment by MrChromebox** [comment]
that has nothing whatsoever to do with my script, it's simply SeaBIOS being buggy / behaving differently on a cold vs warm reboot.

that said, LINK is well past EOL, and you'd be much better served removing the firmware WP screw and flashing my UEFI Firmware instead of screwing around with RW_LEGACY/SeaBIOS

**Comment by k2arim99** [comment]
That's helpful thanks!
