### ISSUE TITLE
firmware-util.sh: line 52: ./sources.sh: No such file or directory

### ISSUE THREAD

**Issue by bam80** [MrChromebox/scripts#184]
```
$ cd; curl -LO mrchromebox.tech/firmware-util.sh && sudo bash firmware-util.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   185    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  1441  100  1441    0     0    811      0  0:00:01  0:00:01 --:--:--   811

Downloading supporting files...
firmware-util.sh: line 52: ./sources.sh: No such file or directory
firmware-util.sh: line 53: ./firmware.sh: No such file or directory
firmware-util.sh: line 54: ./functions.sh: No such file or directory
firmware-util.sh: line 60: prelim_setup: command not found
```

PS: looks like it's a problem with snapped curl: it creates it's hierarchy within /tmp/snap.curl, thus an error:
```
$ sudo ls -R /tmp/snap.curl
/tmp/snap.curl:
tmp

/tmp/snap.curl/tmp:
firmware.sh  functions.sh  sources.sh

**Comment by MrChromebox** [comment]
boot a live USB with a sane version of curl? I can adjust to use TMP=mktmp() or something I guess

**Comment by bam80** [comment]
As workaround I reinstalled curl with apt.
Setting TMP won't probably help as it seems still interpreted within that special /tmp/snap.curl/ directory..

**Comment by PSCGOhio** [comment]
I;m also getting that same error, but it gets a 400 error trying to source the 3 files?  I manually got them, but the way  Ubuntu is set up with 22.04 on my Dell Chromebook I can't get perms to copy them where they belong.  And I can't get into recovery mode nor update from SeaBIOS to fix that.  Ideas?  Can the script be rewritten to find those 3 where I have them?  symbiotic link or something?

**Comment by bam80** [comment]
> As workaround I reinstalled curl with apt.

@PSCGOhio did you try that?

**Comment by PSCGOhio** [comment]
Yep, if it was in the thread it was tried.  The same obstacle of no SU
abilities stops me cold.

**Comment by MrChromebox** [comment]
@PSCGOhio what are you trying to do? There is no Recovery Mode or SeaBIOS with my UEFI firmware. snap-installed curl is problematic, install via apt instead. You should have no problem then

**Comment by cutervino** [comment]
Problem solved: I installed Ubuntu 23.04 on my Asus Chromebook C302C. To make a long story short, I managed to installed Mrchromebox. but no sound (Dummy sound), Bluetooth not working, etc. So I decided to install Qube OS, and it failed, leaving my Chromebook bricked. I found at medium.com/techtalkers, the solution using Ubuntu live usb. It failed with 22.04.2 (No curl), it was a mess: freezing, screen up side down, etc. Then I tried with 23.04 and I had the same problem Bam80 describes. But I didn't have the problems of 22.04.2. It was kind of neat, so when it failed, just out of frustration, I hit Install Ubuntu 23.04 instead of try. And it was lightning fast. It updated neatly, I installed immediately Nordvpn, VLC.  So far the only problem is no internal speakers sound, (Bluetooth works) and no tablet mode, but that's nothing compared with a bricked Chromebook and happy to say goodbye to Google consumerism. All this started because Google announced no more support starting some fatidic day of June 2023. I'm getting rid of all Google services, just to save the world.

**Comment by cutervino** [comment]
Ah, I forgot to state that the freaking rabbit still appears at the beginning of booting

**Comment by MrChromebox** [comment]
@cutervino my FAQ is pretty clear about needing to use apt-installed curl, not snap-installed, on newer versions of Ubuntu . There's simply no way to work around the limitations of snap-installed curl.

> Ah, I forgot to state that the freaking rabbit still appears at the beginning of booting

I'm not sure I understand the problem, that's the firmware boot splash screen

**Comment by cutervino** [comment]
I apologize MrChromebox, I shouldn't have used that word. No problem at all. I'm neither a geek, nor a techy guy. I'm just a citizen of the world that wants to help with the climate change. It's just that, when Ubuntu asked me to erase the whole disk at installation, I thought it'll delete everything. We all know your hard work on this project, and we thank you for that. 
So I take this opportunity to ask you if there's a way to get the sound working and if it's possible to get tablet mode. I appreciate your help.

**Comment by MrChromebox** [comment]
> It's just that, when Ubuntu asked me to erase the whole disk at installation, I thought it'll delete everything

yes, it will erase everything on the target installation disk. The firmware is not stored there :)

>  if there's a way to get the sound working and if it's possible to get tablet mode. I appreciate your help.

on CAVE? Yes, but not using Ubuntu. Check the links on my FAQ page, as well as the #linux channel on the chrultrabook Discord server.
