### ISSUE TITLE
Unable to read firmware

### ISSUE THREAD

**Issue by stangosnell** [MrChromebox/scripts#278]
On Asus chromebox CN60, long ago flashed SeaBIOS, and have been running pure Linux for several years.  Decided to revert to ChromeOS, so ran the firmware utility script from both Debian Bullseye and Fedora 38, and get the same error, "Unable to read firmware".  Is this hardware just too old to revert to ChromeOS?  This is the output after the error:

flashrom dc8caac9-dirty on Linux 6.2.15-300.fc38.x86_64 (x86_64)
flashrom is free software, get the source code at https://flashrom.org

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
coreboot table found at 0x7f73d000.
Found chipset "Intel Lynx Point LP Mainstream".
This chipset is marked as untested. If you are using an up-to-date version
of flashrom *and* were (not) able to successfully update your firmware with it,
then please email a report to flashrom@flashrom.org including a verbose (-V) log.

Flashrom is the latest available from both distros.  I have not reported to flashrom, I don't know how to get a verbose log using the script.

**Comment by MrChromebox** [comment]
> Decided to revert to ChromeOS

please do not, the latest update the CN60 got was years ago. The proper path forward is to upgrade to the UEFI Full ROM firmware, then install ChromeOS Flex

> so ran the firmware utility script from both Debian Bullseye and Fedora 38, and get the same error, "Unable to read firmware". Is this hardware just too old to revert to ChromeOS? 

nothing to do with the age of the hardware, everything to do with the kernel config + version of flashrom used by the script. Reporting the issue to flashrom.org will be ignored, since the script is not using upstream flashrom, but a custom build of the chromium fork.

I recommend live-booting Ubunut 2210/2304, since the script is known to work there, then following my advice above. Going back to stock firmware is not supported on EOL devices.
