### ISSUE TITLE
Having an issue on my chromebook

### ISSUE THREAD

**Issue by mmz6** [MrChromebox/scripts#282]
It keeps saying 

SecureBoot status: disabled

Booting frm 'eMMC Device' failed; verify it contains a 64-bit UEFI OS

Press any key to continue booting. . .

Even though I have my USB plugged in I go into the continue booting part and type exit and I can't find my USB there. Thankfully I have my ROM but I have no clue on how to use it, can you guide me?

**Comment by erubescent** [comment]
Hello, what OS are you attempting to install and what are you using to create the USB? When you first boot the machine up, are you able to press `esc` and access the boot options? It should look something similar to [this](https://github.com/MrChromebox/scripts/assets/13592273/04f8d0b7-ca9c-4d19-86fe-7d8b2b1c43bf). In my specific case, I have [Fedora XFCE](https://spins.fedoraproject.org/xfce/) installed since it is lightweight and not demandant on very many resources.

If you don't see your USB, it is possible that it's formatted incorrectly. Use [balenaEtcher](https://etcher.balena.io/) to flash your drive and make sure the image you are downloading is 64-bit and not 32-bit.
