### ISSUE TITLE
mrchromebox.tech is down

### ISSUE THREAD

**Issue by lukeb2e** [MrChromebox/scripts#369]
Hello,

the linked website in the readme (https://mrchromebox.tech/) is currently unavailable.

**Comment by MrChromebox** [comment]
working on it

**Comment by rosanyadav08** [comment]
How much time it will take to be done

**Comment by MrChromebox** [comment]
no idea

**Comment by rosanyadav08** [comment]
Can we get any other way to process it

**Comment by MrChromebox** [comment]
don't you think I would have provided that info if it were an option?

**Comment by Mrnermaler** [comment]
you can get the firmware script to download by running sudo bash -c "cd; curl -LOk https://raw.githubusercontent.com/MrChromebox/scripts/master/firmware-util.sh && sudo bash firmware-util.sh"
into ternmal aussming your not installing firmware

**Comment by Mrnermaler** [comment]
you can restore stock chrome os you can change gbb flags or even change HWID

**Comment by Mrnermaler** [comment]
@MrChromebox do you know whats causing your site to not work like a ddos or a bug in whats ever you use to host like windows server or apache

**Comment by Mrnermaler** [comment]
you can still ping mrchromebox.tech with crosh PING 198.100.145.128 (198.100.145.128) 56(84) bytes of data.

this is mrchromebox website ip

**Comment by MrChromebox** [comment]
JFC people, have some damn patience.

**Comment by Mrnermaler** [comment]
i am im just saying and wondering what cause the website to stop working

**Comment by MrChromebox** [comment]
this thread strongly suggests otherwise

**Comment by guicompeng** [comment]
![](https://media1.tenor.com/m/3OZu_n2PL-QAAAAC/star-wars-yoda.gif)

**Comment by Emperor-24** [comment]
@MrChromebox I appreciate the work you are doing here, great. But please I have clients waiting to take their chromebook I wanted to download the Uefi firmware and run windows on the chromebook, the clients are not being patient. Is there any other way I can do that?

**Comment by rosanyadav08** [comment]
Sir we are waiting for your site to be restored, 😞

**Comment by Emperor-24** [comment]
This is really frustrating and hindering loads of jobs and profits too.. A feedback from @MrChromebox would be great

**Comment by ferrellsl** [comment]
> This is really frustrating and hindering loads of jobs and profits too.. A feedback from @MrChromebox would be great

@rosanyadav08, @Emperor-24, @Mrnermaler 

Do you guys realize that Mr. Chromebox does this work for free and that he has a real job elsewhere to pay his bills?  You guys are the most impatient pricks that I have ever seen.  Since you're using his work to make profits maybe you should consider sending him a donation instead of whining about his site being down.

**Comment by AverageJuliet** [comment]
Look if you morons really want your 20$ Chromebooks running Coreboot then compile and flash it yourself, its not hard.
Leave this man alone and let him recover his webserver in peace for fucks sake.

**Comment by MrChromebox** [comment]
> This is really frustrating and hindering loads of jobs and profits too.

sounds like I really need to start charging for my firmware

**Comment by MrChromebox** [comment]
easy solution -- I would have the builds compiled against the device serial, and fail to boot (or show an error) if there was a serial mismatch

**Comment by ferrellsl** [comment]
> > This is really frustrating and hindering loads of jobs and profits too.
> 
> sounds like I really need to start charging for my firmware

Maybe add a line of text to the boot splash screen that says if you paid for the firmware that you should ask for a refund.

**Comment by WeirdTreeThing** [comment]
Brick the chromebook if there is a serial mismatch, then offer a paid unbricking service.

**Comment by rosanyadav08** [comment]
> > This is really frustrating and hindering loads of jobs and profits too.
> 
> sounds like I really need to start charging for my firmware

Sorry sir but we really respect you and the work you are doing it helps everyone one

**Comment by AverageJuliet** [comment]
![20240223_111759](https://github.com/MrChromebox/scripts/assets/134985726/7329caf2-09e9-42e9-8161-3a8c3b24b974)

Mrchromebox  i want a refund....

**Comment by wearrrrr** [comment]
> sounds like I really need to start charging for my firmware

Honestly at this point maybe you should, your website goes down for a day and immediately a wave of people come into github issues, for anyone who is really fucking impatient, maybe try archive.org? harassing this guy isn't gonna get you anywhere

**Comment by ferrellsl** [comment]
@Emperor-24

I'm just going to reiterate what ninelore said earlier. "You shouldn't rely on one-man voluntary work for "jobs and profits" and then have the audacity to complain"

You already knew that this project is hosted on Github, so you would have already known that the work done here is for free and opensource, so stop trying to sound like you just stumbled onto the project like some sort of little lost lamb, and stop trying to portray yourself as some sort of victim.  All you've done is complain since your very first post.

**Comment by Emperor-24** [comment]
@MrChromebox Thanks for your polite response. Is there anyway you'll need an assistance from us in getting your server back up?

**Comment by ferrellsl** [comment]
> @MrChromebox Thanks for your polite response. Is there anyway you'll need an assistance from us in getting your server back up?

Maybe you should funnel some of your profits to Mr. Chromebox so he has an incentive to get the site back up for you.

**Comment by Emperor-24** [comment]
@ferrellsl
 Must you people always sound so rude and insulting? Is this how you are? Are you a bullie?

Am just getting to know about Github some hours ago and signed up few hours ago too don't you get that.. I recently learnt how to run windows on chromebook some days back and the @MrChromebox site went down..

Why are you always feeling everyone is lying.

**Comment by ferrellsl** [comment]
> @ferrellsl Must you people always sound so rude and insulting? Is this how you are? Are you a bullie?
> 
> Am just getting to know about Github some hours ago and signed up few hours ago too don't you get that.. I recently learnt how to run windows on chromebook some days back and the @MrChromebox site went down..
> 
> Why are you always feeling everyone is lying.

Must you always complain?  Must you always be a  "victim"?  I don't feel that everyone is a liar, but I do feel that YOU are a liar. 
Why are you lying about not knowing that this is a free and opensource project hosted on github?  The entire purpose of github is to host  free and opensource projects, so you obviously knew that, yet you complained anyway about losing profits and customers when Mr. Chromebox's script site went down.  And why won't you even address the fact that Mr. Chromebox gladly accepts donations for his work and then not send him a donation since you're obviously making money from his hard work?  I sent him $50 USD some months ago for his fantastic work.  Why do you think that it's OK to make a profit from free and opensource work and then complain about it when you're losing money and then come back again to play the victim?  At this point I hope the site stay down just to spite you and that when/if it does come back online, that Mr. Chromebox starts charging a fee to keep pricks like you away.

**Comment by OtterCodes101** [comment]
if you guys REALLY need the firmware, just compile it yourself 😒
