### ISSUE TITLE
possible brick after custom UFI Firmware

### ISSUE THREAD

**Issue by bigt11** [MrChromebox/scripts#60]
I have a asus cn62 in the past I used your setup-kodi.sh just fine.

My chromebox was in developer mode, I hit  CTRL-ALT-F2 to get to command line, I entered "chronos"

I ran 
`curl -L -O https://mrchromebox.tech/setup-kodi.sh && sudo bash setup-kodi.sh`

I choose 6, the backed up the current firmware.
It seemed to attempt to update the firmware to coreboot_tiano-guado-mrchromebox_20180204.rom but failed.  It said "An error occurred flashing the Full ROM firmware. DO NOT REBOOT!"

I tried 6 again and it failed.  So I though, ok ill just do a dual boot, so I choose option 1 and it said it worked and I should reboot to allow chrome os to "repair"

Upon reboot, a black screen via hdmi.  The power white light comes on for about 30 seconds then turns off.  I have not been able to see anything on screen when it powers on.  

Did I brick it, or can I somehow restore the saved firmware.  I tried to do the standard chrome OS recovery with the reset button but noting appears on screen.

Let me know if you have any ideas for recovery.

**Comment by MrChromebox** [comment]
> Did I brick it, or can I somehow restore the saved firmware

yes to both.  you bricked it by not restoring your stock firmware backup after it gave an error flashing the UEFI Full ROM firmware.  At that point, you system was in an unstable/undetermined state, and restoring the stock backup was the only safe move.  Switching to a dual boot setup would first require you to restore the stock backup so you'd be starting from a working baseline.

since your device is bricked, you'll need to either reflash the firmware using an external programmer, or have me do it for you.  Shoot me an email at MrChromebox at gmail and we'll discuss the options to get you back up and running
