### ISSUE TITLE
Script is for 64 bit only?

### ISSUE THREAD

**Issue by optio50** [MrChromebox/scripts#85]
Tried to run the firmware script to install Full Rom but it says its for 64 bit only.
I am having difficulty booting from an SD card  with my current firmware John Lewis 1.9.0.59
So Im kinda in a pinch here cant run the script and cant boot a 64 bit OS from SDcard / USB

Any suggestions?

**Comment by MrChromebox** [comment]
the script is 64-bit only because it downloads a few precompiled binaries (flashrom, cbfstool, gbb_utility) in order to do everything it needs to do, and those binaries are 64-bit only.  It's likely possible to simply to simply download/flash the correct firmware file directly.  Shoot me an email at mrchromebox at gmail and I'll get you sorted out
