### ISSUE TITLE
Gemini Lake Processor Support

### ISSUE THREAD

**Issue by TravisArmstrong** [MrChromebox/scripts#89]
I'm using a new (manufactured Fed 2019) Acer R815TN that includes an Intel Celeron N4100 processor. When loading the firmware script the "CPU Type" is blank and I noticed Gemini Lake not listed on supported platforms. Is there a specific reason for this? Seems kind of like an oldish platform but it's obviously still being used on new products, perhaps due to the recent Intel CPU shortages.

**Comment by MrChromebox** [comment]
GeminiLake is the successor to Apollolake, it's the latest Atom-based microarchitecture, and devices are just now coming to market -- which is why there's no support yet. Shoot me an email @gmail and I'll provide you a test build, and if it works I'll push to the main/public script. Be sure to include your device/board name (or HWID)

**Comment by Git-Ham** [comment]
Is there any update to this by any chance? I'm toying around with a newer Lenovo 500e (PHASER360) with a Gemini Lake processor and am receiving the following error,

Unknown or unsupported device (phaser): Cannot update RW_LEGACY firmware.

Thank you!

**Comment by MrChromebox** [comment]
there is no RW_LEGACY firmware available yet, sorry

**Comment by StefanoMilani** [comment]
Hi, is there any update about the GeminiLake support?

**Comment by MrChromebox** [comment]
still broken on Google's end

**Comment by Jaydog7k** [comment]
How's the future of Gemini Lake look? I bought the HP x360 14b BLOOGUARD instead of 14 SONA smh.

**Comment by MrChromebox** [comment]
as dark as ever, unfortunately

**Comment by animeking9901** [comment]
I'm open to testing a build for BLOOGUARD if it's possible to make a test build

**Comment by MrChromebox** [comment]
test build for what? We know with 100% certainty that RW_LEGACY is broken, I can verify that here on my AMPTON test device. And I have no desire to add UEFI support for the 30+ APL/GLK boards out there just to have people bitch about things (mostly windows) not working

**Comment by animeking9901** [comment]
well that sucks,as id be using Linux with UEFI,or RW_LEGACY,i just
wanted to run Linux with maybe wine,which crostini and crouton dont
seem to like too much

**Comment by MrChromebox** [comment]
you realize that audio, touchscreen, rotation, etc will all not work, or work far less optimally than under ChromeOS? These devices are just not well supported under mainline Linux distros

**Comment by animeking9901** [comment]
Touch screen rotation I can live without but audio good grief let me know
when main line kernel support improves and then I'll reconsider

**Comment by MrChromebox** [comment]
I have no idea when that will be. I can't possibly keep track of support for 100+ devices (or even a dozen or so platforms)

**Comment by msangel** [comment]
Wine is not needed. Sound and touchscreen we can live without. For terminal server there are not much requirements. Just booting, minimal video, keyboard, maybe mouse and network.

**Comment by animeking9901** [comment]
Just because you don't need wine doesn't mean others don't

**Comment by Thomas-DaxBrin** [comment]
Hello,

Thanks you for your job mrChromeBox.

I have problem in my legacy mode the bootloader tianoCore don't start After press numeric key.

I would like update or change this to fix bug but my FW version is unknow (Google_bobba.11297.252.0)

Have you more information of this problem ?

**Comment by MrChromebox** [comment]
@Thomas-DaxBrin unfortunately I don't support Geminilake Chromebooks at this time

**Comment by LiamTheProgrammer** [comment]
I have one of these chromebooks too and I really want to be able to install Linux on it, but I can't yet because this isn't supported. Will support for this be added anytime soon?

**Comment by MrChromebox** [comment]
@LiamTheProgrammer nope, no intention of adding GeminiLake UEFI Full ROM support

**Comment by animeking9901** [comment]
Ouch. Glad I finally just bought a thin client to mess with instead

**Comment by uniqueusernamelol** [comment]
> @LiamTheProgrammer nope, no intention of adding GeminiLake UEFI Full ROM support

have you given up on trying, or is there still any development or progress or just anything trying to get it working for gemini lake?

**Comment by MrChromebox** [comment]
there is no impediment to UEFI Full ROM support for GeminiLake devices other than my time and willingness to make it happen. Right now I don't have much of either, since doing so will just unleash more hoards of users wanting to run Windows on them

**Comment by uniqueusernamelol** [comment]
> there is no impediment to UEFI Full ROM support for GeminiLake devices other than my time and willingness to make it happen. Right now I don't have much of either, since doing so will just unleash more hoards of users wanting to run Windows on them

is there legacy boot mode now (RW_legacy) or is that still broken

**Comment by MrChromebox** [comment]
RW_LEGACY/Alternative bootloader menu on GLK cannot boot SeaBIOS nor Tianocore currently

**Comment by uniqueusernamelol** [comment]
> there is no impediment to UEFI Full ROM support for GeminiLake devices other than my time and willingness to make it happen. Right now I don't have much of either, since doing so will just unleash more hoards of users wanting to run Windows on them

how long has it taken you in the past to get uefi full rom on other architectures and what is a potential incentive to get you to develop it since idk anybody else doing this

**Comment by MrChromebox** [comment]
> how long has it taken you in the past to get uefi full rom on other architectures and what is a potential incentive to get you to develop it since idk anybody else doing this

oh it's already working, it's literally just a question of do I want to build/distribute ROMs for another ~15 devices, given that they won't run Windows (and that's what most users will want), and the lack of ability to unbrick due to Suzy-Q cables being NLA

**Comment by animeking9901** [comment]
Personally I'd just setup some sort of automation that automatically
deletes+bans any issues/users that even say the word windows. Problem solved

**Comment by MrChromebox** [comment]
from Github? reddit? my email? my twitter?

**Comment by uniqueusernamelol** [comment]
> 

there are genuine reasons to be talking about windows?

**Comment by oojih** [comment]
Hi, i have an issu, i'm new to this so dont be rude plz
I followed your tutorial to get the acces to the bios of my hp chromebook x360 but even when i disabled the WP i cannot install RW_Legacy cause i got this error message "Unknown or unsupported device (bloog); cannot update RW_LEGACY firmware." 
I made a bootable usb device wtih kali linux on it but i dont know how could i install it without the bios, i'm trying since many days already, if you have an answer for me or if someone could help me it'll be nice 
(Sorry for the bad english i'm french ^^⁾

**Comment by animeking9901** [comment]
Not happening rn,due to whiny windows using bitches so the developer isn't
updating things rn

**Comment by oojih** [comment]
damn its a succes for me but the version of kali that i have is an older one 
quite sad but its a first time so i'm still happy to make this by myself ^^

**Comment by animeking9901** [comment]
I wonder how hard it would be to port full UEFI myself

**Comment by MrChromebox** [comment]
as of right now, I provide one-off unsupported UEFI ROMs for GLK devices upon request via email. Flash at your own risk.

**Comment by RaineX3333** [comment]
Hi Sir MrChromebox can i request a uefi roms for my hp chromebook 14a Booglet Gemini lake thank you!

**Comment by uniqueusernamelol** [comment]
> Hi Sir MrChromebox can i request a uefi roms for my hp chromebook 14a Booglet Gemini lake thank you!

you are supposed to email him at mr.chromebox@gmail.com, not reply to this thread

**Comment by hexdump0815** [comment]
in case someone is only interested to get linux running on its gemini lake chromebook and does not care about the fact, that some hardware is not really working (sound, wifi, deep sleep, ...) it might be worth to have a look at https://github.com/hexdump0815/imagebuilder/tree/main/systems/chromebook_octopus and the debian/ubuntu images linked from there - those are using the native chromebook depthcharge booting to boot the linux kernel/system via ctrl-u - it works quite well with mainline kernels - some more info about how the kernel is built and prepared can be found here: https://github.com/hexdump0815/linux-mainline-x86-64-kernel/blob/main/readme.cbo

best wishes - hexdump

**Comment by LameLad007-Sudo** [comment]
So question, I'm using a Dell Chromebook 3100 that aperantly has Legacy Boot Support (when the utility script is ran, it mentions the stock chrome BIOS w/RW_LEGACY), would it be possible to get it working since it mentions this despite it using gemini lake? (It's a 2020 model.)

**Comment by LameLad007-Sudo** [comment]
The specific gemini lake one is the N4000 Intel Celeron.

**Comment by LameLad007-Sudo** [comment]
![Screenshot 2022-04-07 11 43 06 PM](https://user-images.githubusercontent.com/100988699/162365374-11e5e5de-f40d-410d-947d-fa23b9084ae8.png)
So I have no clue if this may or may not be hopeless, but I don't know if this even is possible, but I got hope it might be.

**Comment by MrChromebox** [comment]
@LameLad007-Sudo no, there are no payloads which are functional being used as RW_LGEACY payloads on GeminiLake Chromebooks (other than maybe u-boot).

**Comment by Shazia34** [comment]
when will support for it come?

**Comment by MrChromebox** [comment]
@Shazia34 when will what come? this issue is closed for a reason

**Comment by saturnnights** [comment]
okay, i guess this is as good a place as any.  below is a gist link that contains my coreboot/depthcharge CBMEM buffer, first showing a handoff to a built tianocore payload via altfw autoboot, and second showing handoff to chromeos kernel via dev mode boot.

[https://gist.github.com/saturnnights/70aac966e1f8789ec43ab9001295009c](url)

this is my BLUEBIRD [samsung chromebook 4, related to CASTA, OCTOPUS base board, gemini lake], booting a tianocore payload via RW_LEGACY with stock coreboot/depthcharge [active firmware Google_Casta.11297.242.0].

below are the steps that i took to build the tianocore payload, and how i added it via cbfstool and flashed it.

1. git clone https://review.coreboot.org/coreboot
2. cd coreboot
3. git submodule update --init --checkout
4. make crossgcc
5. make menuconfig
6. select board type of google casta
7. make
8. copy coreboot/build/UEFIPAYLOAD.fd to chromebook
9. flashrom -p host -r [FLASH FILE]
10. cbfstool [FLASH FILE] remove -r RW_LEGACY -n altfw/tianocore
11. cbfstool [FLASH FILE] remove -r RW_LEGACY -n cros_allow_auto_update
12. cbfstool [FLASH FILE] add-payload -r RW_LEGACY -n altfw/tianocore -f UEFIPAYLOAD.fd -c lzma
13. flashrom -p host -i RW_LEGACY -w [FLASH FILE]
14. ensure you can boot legacy/altfw: crossystem dev_boot_altfw=1
15. configure legacy/altfw to boot default: crossystem dev_default_boot=altfw
16. power off
17. power on, wait
18. tianocore, GRUB

coreboot used at time of writing:
commit e3ed9cacaa2b372a3efce95308d15aea3806fbf9
tianocore used at time of writing [i think]:
branch uefipayload_202107

there is still some weirdness.  trying to boot it via CTRL-L and selecting a bootloader doesn't work.  it appears to only work at this time via dev_default_boot being set to altfw and letting it autoboot.  i haven't dug in to why that is.

to make sure that i didn't somehow disrupt something on my BLUEBIRD, i picked up a second BLUEBIRD off of ebay, left firmware write protected, updated only the RW_LEGACY region, configured dev_default_boot for altfw, waited for the timeout, and it launched the tianocore payload.

this appears to be a tianocore payload executing via RW_LEGACY on gemini lake.  tested it UEFI booting an operating system with a finnix live image.

maybe someone else can repro?

**Comment by MrChromebox** [comment]
> there is still some weirdness. trying to boot it via CTRL-L and selecting a bootloader doesn't work. it appears to only work at this time via dev_default_boot being set to altfw and letting it autoboot. i haven't dug in to why that is.

I only ever tried via the alternative bootloader menu, not as default via crossystem or GBB Flags. interesting there is a difference, implies that it's the AltFw menu that's breaking things

**Comment by saturnnights** [comment]
>interesting there is a difference, implies that it's the AltFw menu that's breaking things

that's what it looks like from my experimentation.  it appears to be possible to boot the different entries in the altfw list directly from the "os verification is off" screen by pressing a number corresponding to the entry index in altfw/list within RW_LEGACY. 

[didn't know that was an option, found that by digging through the vboot_reference source tree]

but if you try to do something that should "leave" the altfw menu, it appears to hang.  that includes the esc key, which should return you to the "os verification is off" screen to perform another action, based on my reading of the code.

so, with this poking around, the following appear to happen:

- if dev_default_boot=altfw, will boot the zeroth index in altfw/list after boot timeout.  the payload that comes with it doesn't appear to work [and isn't guaranteed to, i get it], but building and putting tianocore in does work
- no matter what the default boot option is, either via crossystem, GBB, or FWMP, one can still boot the different entries within the altfw list by using the number keys.  this means that dev_default_boot could be disk or usb, but if you, say, press 0 [after swapping the payload out with one that works], tianocore will load.

so, as long as someone doesn't make use of CTRL-L to try to do altfw/legacy boot, you can still use that feature, and even select different payloads.  if you don't remember what you had loaded, you could press CTRL-L to display the menu, see the number you want, power off, power on, then press that number to boot the corresponding payload.

this is clearly not working "correctly", but it appears the situation might not be as bleak as "FW_LEGACY doesn't work at all".

**Comment by hexdump0815** [comment]
@saturnnights - i can confirm that your procedure works - tested it on a blooglet octopus (hp chromebook 14a) booting some own uefi debian image ... this is very cool! ... here are my notes about it (had to add some extra steps to make it fully work): https://github.com/hexdump0815/coreboot-cb-rw-uefi-payload

is this supposed to work only for octopus, only for newer chromebooks, for some chromebooks or for most chromebooks supported by coreboot?

even wifi was working out of the box (which always was very troublesome using chromeos or mainline kernels and kpart depthcharge booting) - sleep does not work (but i think this is a problem on newer chromebooks in general maybe - ?), but at least s2idle suspend works ... sound is most probably a bit more tricky to get working, but i think this is quite normal for newer systems

this is very nice, thanks for sharing this and while i'm here thanks as well to @MrChromebox for all your great work!

best wishes - hexdump

**Comment by saturnnights** [comment]
@hexdump0815 to answer your question, i will provide some guesses and speculation, because i have not put in all of the effort to track each branch change to be 100% certain.  sprinkle in some "i think", "i'm not sure", "maybe", etc. throughout my response.

two development trains happened at the same time.  one being the chromeos/chromiumos branches of coreboot, depthcharge, and vboot.  the other being development and production hardware for chromebooks.

i'll write about the software development first.

"originally", some time in the past early enough that figuring out when isn't important to this conversation, the functionality of "legacy boot" was introduced.  you press CTRL-L at the "os verification is off" screen, it checks through CBFS to locate the payload.  loads into ram, jumps to address, execution proceeds in the payload [with the assumption this is a valid payload].

straightforward, but a touch inflexible.  you could only have one payload.

at some point, development began on changing that subsystem from being "single payload" to "multiple payloads, with a menu", and the feature changed from "legacy boot" to "alternative firmware".  you could upload multiple payloads with different names, adjust a file listing to include them, and pick which ones you want.  pressing CTRL-L would bring up a selection menu to pick which one, and if you use "dev_default_boot=altfw", it would boot whatever was in index 0.  the other bit that i don't think has been well documented is that at the "os verification is off" screen, you can directly boot whichever payload is in which slot in the index file listing by pressing the number key at that screen, without pressing CTRL-L.  this is an intentionally written feature as a shortcut, from what i am reading in the source code.  those with stoney ridge and later can confirm.

neat.  but...now let's talk about the other development train.

given my limited sample size of chromebook hardware [absolutely pales in comparison to @MrChromebox and his contacts], i'll guess like this.  this would be the software development overlayed with the hardware releases per generation.

[this is speculation.  the actual demarcation is not important.  the important bit is that there's an inconsistency, and it's in gemini lake generation chromebooks]

* kaby lake/amber lake and earlier - "legacy boot"
* gemini lake - ???
* stoney ridge and later - "alternative firmware"

alright, the ??? part.  at the point that platform released, the development cycle [sprint?  epic?  triumph?] for completely implementing their plans for alternative firmware wasn't done.  [my guess, my speculation].  some parts don't work, some parts are a bit obscure, but if you know what to do, you can boot payloads on gemini lake.

the "verified boot" codepath was stable, so, they snapshot that code train for gemini lake [octopus] and shipped it.  the "legacy boot"/"alternative firmware" feature feels like it was a "we'll do it if we can, we're doing nice things" but is not a prod shipping requirement [in my eyes].  this means that gemini lake got an unfinished implementation of "alternate firmware".

[https://groups.google.com/a/chromium.org/g/chromium-os-dev/c/F7gUL7-IPQw](https://groups.google.com/a/chromium.org/g/chromium-os-dev/c/F7gUL7-IPQw) this may be something to support this theory.  a notice to the chromium-os-dev lists that the alternative firmware bootloader wasn't quite working right, so, boot it manually by number key.  this was november 2018.  in [https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices/](https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices/), the earliest gemini lake hardware is february 2019.  it's close.  and still speculation.

to the point of how alternative firmware is used in, well, stoney ridge and later.

1. CTRL-L is supposed to invoke a menu.  from that menu, you're supposed to be able to press a number key to select a payload from the contents of "altfw/list" within the RW_LEGACY region within the CBFS flash layout.
2. at the "os verification is off" screen, i think you're also able to press a number key to select a payload, skipping CTRL-L.
3. and finally, if you have "dev_default_boot=altfw", it will use the payload in the 0 index of "altfw/list".

within gemini lake, from my testing, the only thing that i think is broken is number 1 in the above list.  the menu pops up when you hit CTRL-L, but trying to use the menu doesn't work.

numbers 2 and 3 i have repeatedly tested to work on my limited gemini lake hardware.  maybe other gemini lake devices have different branches, but that doesn't make sense when they're supposed to be stabilized on the same reference platform.  i would guess all of gemini lake [octopus] functions like this.

[very much of this is based upon my reading of code, checking the code branches for gemini lake [octopus], apollo lake [coral], and jasper lake [dedede].  i have talked to no one within google, or the chromium os dev team, or the coreboot team, in any capacity outside of my posting these entries on this issue.  i might be completely wrong.  but i don't think i am.  corrections welcome.]

i hope this helps.

**Comment by alpernebbi** [comment]
I looked into this a bit, and it looks like `octopus` boards somewhat fallback to the old `payload` file if there's no `altfw/list` file. I've got a `lick` board, so what I did is mostly:

```bash
curl -L -o lick.rom "https://www.mrchromebox.tech/files/firmware/full_rom/coreboot_tiano-lick-mrchromebox_20220718.rom"
cbfstool lick.rom extract -m x86 -n fallback/payload -f tianocore.elf
cbfstool rw_legacy.cbfs create -m x86 -s 0x1c0000
cbfstool rw_legacy.cbfs add-payload -n payload -f tianocore.elf -c lzma

# On ChromeOS
sudo flashrom -w -i RW_LEGACY:rw_legacy.cbfs
```

It still shows the empty pick-a-bootloader menu when I press CTRL+L, but pressing any number boots into the UEFI flow just fine, no matter when I try it. I booted Debian Installer from it, but didn't test any further.

**Comment by hexdump0815** [comment]
@saturnnights - thanks a lot for your long summary (looks like i missed it when you posted it) - all this might make sense

while we are at this: is there any gbb flag value to set
```
crossystem dev_boot_altfw=1
crossystem dev_default_boot=altfw

**Comment by alpernebbi** [comment]
> i guess "GBB_FLAG_FORCE_DEV_BOOT_LEGACY" is to force the ctrl-l option - "GBB_FLAG_ENABLE_ALTERNATE_OS" might match dev_boot_altfw=1, but is there anything which would match dev_boot_default=altfw? 

It's `GBB_FLAG_FORCE_DEV_BOOT_LEGACY` and `GBB_FLAG_DEFAULT_DEV_BOOT_LEGACY` according to [this commit renaming "legacy boot" things to "altfw"](https://chromium-review.googlesource.com/c/chromiumos/platform/vboot_reference/+/2641346).

**Comment by MrChromebox** [comment]
@hexdump0815 if not running ChromeOS, why are you not using the UEFI Full ROM firmware for your device? RW_LEGACY/Altfw is for dual booting only

**Comment by alpernebbi** [comment]
I see the coreboot logo as splash, and press ESC and select the USB from the Boot Menu.

**Comment by MrChromebox** [comment]
@alpernebbi quite possible the latest Tianocore payload works around issues with the stock firmware which earlier versions did not. Did you try adding altfw/list and selecting from menu that way?

**Comment by hexdump0815** [comment]
@alpernebbi - my idea is to boot uefi via rw payload to have the advantage of uefi (works easily for any kind of linux installers) and rw firmware (no write protect removal required, no suzyqable required, no risk to brick anything, can be easily reverted to chromeos for instance before selling a device) ... i'm running it successfully now this way on a glk bloog device and its very nice - booting looks like: dev-mode-screen -> nice coreboot logo -> logo and escape info -> grub ... it goes directly to grub if installed onto emmc - if running from sd or usb one needs to get into the bios via esc key to select the proper boot device ...

**Comment by hexdump0815** [comment]
oh then looks like this is what most probably makes sense in such a scenario:
```
VB2_GBB_FLAG_DEV_SCREEN_SHORT_DELAY
VB2_GBB_FLAG_FORCE_DEV_SWITCH_ON
```

**Comment by alpernebbi** [comment]
>  Did you try adding altfw/list and selecting from menu that way?

Yeah, this doesn't work. I can run payloads listed in `altfw/list` by pressing their sequence numbers before I enter the menu, but not after then. Not even after I exit the menu. It's not about the payload, it happens with a half-working U-Boot build as well, and it stops error-beeping for the unavailable entries (when there is no 0-numbered default entry).

**Comment by MrChromebox** [comment]
> by pressing their sequence numbers before I enter the menu

wait, what? on what screen? the numbers correspond to the entries in altfw/list, so without that, there's nothing to tie a payload to a number

**Comment by saturnnights** [comment]
@MrChromebox i wrote a little bit about how you can trigger the index slots for booting from the "os verification is off" screen

> the other bit that i don't think has been well documented is that at the "os verification is off" screen, you can directly boot whichever payload is in which slot in the index file listing by pressing the number key at that screen, without pressing CTRL-L. this is an intentionally written feature as a shortcut, from what i am reading in the source code. those with stoney ridge and later can confirm.

the CTRL-L menu is busted.  but selecting/executing the payloads blind works.  or, one could view what's in altfw/list by going into CTRL-L [which won't work], reboot, then use the index number to boot the desired payload.


> so, with this poking around, the following appear to happen:
> 
> * if dev_default_boot=altfw, will boot the zeroth index in altfw/list after boot timeout.  the payload that comes with it doesn't appear to work [and isn't guaranteed to, i get it], but building and putting tianocore in does work
> * no matter what the default boot option is, either via crossystem or GBB, one can still boot the different entries within the altfw list by using the number keys [forgot the important bit.  by using the number keys on the "os verification is off" screen].  this means that dev_default_boot could be disk or usb, but if you, say, press 0 [after swapping the payload out with one that works], tianocore will load.
> 
> so, as long as someone doesn't try to make use of CTRL-L to try to do altfw/legacy boot, you can still use that feature, and even select different payloads. if you don't remember what you had loaded, you could press CTRL-L to display the menu, see the number you want, power off, power on, then press that number to boot the corresponding payload.
> 
> this is clearly not working "correctly", but it appears the situation might not be as bleak as "RW_LEGACY doesn't work at all".

**Comment by MrChromebox** [comment]
@saturnnights that absolutely should not work, I'll have to check the depthcharge code and see what's going on

**Comment by saturnnights** [comment]
> @saturnnights that absolutely should not work, I'll have to check the depthcharge code and see what's going on

https://groups.google.com/a/chromium.org/g/chromium-os-dev/c/F7gUL7-IPQw

> Hi,
>
> Just a note for those who want to boot into TianoCore from dev mode
with recent firmware.
>
>There is a new Alternative Firmware (altfw) feature to support this, with:
>
> USE="-cb_legacy_tianocore altfw tianocore" emerge chromeos-bootimage
>
> (the old cb_legacy_tianocore is not used anymore and will soon go away)
>
> Then you press '2' at the dev-mode screen to boot TianCore at the
> dev-mode screen. Ctrl-L will soon produce a menu of available
> bootloaders. For now it *should* boot Tianocore but I have a report
> that it does not. So please use '2' for now.
>
> Regards,
> Simon

and despite that, it is even referenced in the chromius-os-dev group to boot tianocore using numbers at the dev-mode screen [os verification is off] because the menu is broken.  and i've used it a *lot*.  which is why i wrote this all out to try to find someone else to see if it does work.  and others here have also found it to work.

**Comment by alpernebbi** [comment]
See [vboot_ui.c in vboot_reference](https://chromium.googlesource.com/chromiumos/platform/vboot_reference/+/refs/heads/firmware-octopus-11297.B/firmware/lib/vboot_ui.c) lines, lines 192 and 428. The first one is for the altfw menu, and the other for the main warning screen.

And see [vboot/callbacks/legacy.c in depthcharge](https://chromium.googlesource.com/chromiumos/platform/depthcharge/+/refs/heads/firmware-octopus-11297.B/src/vboot/callbacks/legacy.c) for the fallback to a `payload` file when there's no `altfw/list`.

**Comment by saturnnights** [comment]
yep.  i was digging through firmware-coral, firmware-octopus, and firmware-dedede, to see how it was [legacy, apollo lake], what we're dealing with in gemini lake, and what it became [altfw, jasper lake].  that's why i feel like gemini lake shipped with altfw mid-development, because hardware was ready, and verified boot was working.  all of the keyboard hooks were there, but some parts were incomplete.

it seems that for users on gemini lake, having them press the zero key instead of CTRL-L [after swapping out the tianocore payload] would have legacy/altfw working for them.  it's that straightforward.

**Comment by MrChromebox** [comment]
man, what a shitshow. I could push a fix for the octopus branch, but there's little hope it would actually make it into a production firmware update anytime soon. I guess for now I'll add a RW_LEGACY payload for GLK with no menu and document the workaround

**Comment by alpernebbi** [comment]
> it seems that for users on gemini lake, having them press the zero key [or the two key, since that's the default index within altfw/list] instead of CTRL-L [after swapping out the tianocore payload] would have legacy/altfw working for them. it's that straightforward.

It's even better without the `altfw/list` file. Pressing CTRL+L tells you to "Press a numeric key to select an alternative bootloader" with no options and pressing any number runs the (single) alternative bootloader.

**Comment by saturnnights** [comment]
we definitely have some options.  i'm glad we've figured out some different ways to break though "no RW_LEGACY for gemini lake".

**Comment by MrChromebox** [comment]
pushed an update to my script with an updated RWL payload for GLK, give it a try if you would

**Comment by saturnnights** [comment]
> pushed an update to my script with an updated RWL payload for GLK, give it a try if you would

pulled down the firmware-util script and used it to install the RW_LEGACY image, but it's not launching here [via CTRL-L and pressing any number].

also tried extracting the payload from what was flashed and inserting it in place of altfw/tianocore for my existing RW_LEGACY image and it isn't launching when pressing 0 or 2.

something doesn't seem right with that payload for some reason.

**Comment by saturnnights** [comment]
```
vb2_developer_ui: VbBootDeveloper() - user pressed Ctrl+L; Try alt firmware
vboot_draw_screen: screen=0x212 locale=0
backlight_update called but not implemented.
ERROR: No file header found at 0x1bffc0x - try next aligned address: 0x1c0000.
get_altfw_list: altfw list not found
vb2_altfw_ui: VbBootDeveloper() - user pressed key '0': Boot alternative firmware
tpm_get_response: command 0x121, return code 0x0
ERROR: No file header found at 0x1bffc0x - try next aligned address: 0x1c0000.
get_altfw_list: altfw list not found
Loading payload into RAM
CODE/DATA: dst=0x800000 dst_len=5832704 src=0x30208618 src_len=782134 compression=1
tpm_cleanup: add release locality here.
Shutting down all USB controllers.
Finalizing coreboot
Exiting depthcharge with code 8 at timestamp: 5832088
Starting payload at 0x801626...
```

nothing exciting in CBMEM when trying to launch the payload.  it just hangs.  when i do it with my tianocore build installed as "payload" with no other CBFS contents, it works as @alpernebbi describes.

my chromebook [bluebird, octopus] doesn't like the taste of that payload, @MrChromebox

**Comment by alpernebbi** [comment]
Doesn't work for me either. No error beeps, just hangs.

**Comment by MrChromebox** [comment]
hmm, just a normal build from the uefipayload_202207 edk2 branch. Boots here on any given device as main payload

**Comment by saturnnights** [comment]
```
~/coreboot/payloads/external/tianocore/mrchromebox$ git status
HEAD detached at origin/uefipayload_202107
nothing to commit, working tree clean
```
[octopus-bluebird_casta.config.txt](https://github.com/MrChromebox/scripts/files/9611837/octopus-bluebird_casta.config.txt)

attached is my coreboot build config.  i had used whatever came in head/master from https://review.coreboot.org/coreboot and basically ignored the whole coreboot build part, focusing on the generated payload that came out from selecting the tianocore payload.

that specific part of my config:

```
#
# Payload
#
CONFIG_PAYLOAD_TIANOCORE=y
CONFIG_PAYLOAD_FILE=build/UEFIPAYLOAD.fd
CONFIG_PAYLOAD_OPTIONS=
CONFIG_TIANOCORE_UEFIPAYLOAD=y
CONFIG_TIANOCORE_REPOSITORY=https://github.com/mrchromebox/edk2
CONFIG_TIANOCORE_TAG_OR_REV=origin/uefipayload_202107
CONFIG_TIANOCORE_RELEASE=y
CONFIG_TIANOCORE_HAVE_EFI_SHELL=y
CONFIG_TIANOCORE_PRIORITIZE_INTERNAL=y
CONFIG_TIANOCORE_PS2_SUPPORT=y
CONFIG_TIANOCORE_SD_MMC_TIMEOUT=1000
CONFIG_COMPRESSED_PAYLOAD_LZMA=y
CONFIG_COMPRESS_SECONDARY_PAYLOAD=y
```

i can try building based on uefipayload_202207 and see if that changes anything over here.

**Comment by saturnnights** [comment]
ooookay.  well, the tianocore payload i just generated from uefipayload_202207, via the coreboot build process, booted into UEFI shell just fine.  ran the build, copied UEFIPAYLOAD.fd to the chromebook, swapped it out for "payload" in RW_LEGACY CBFS, and it booted.

now i'm definitely confused.
